image: node:13-alpine
cache:
  paths:
    - node_modules/

before_script:
  - npm install -g yarn --cache-min 99999999
  - yarn

pages:
  script:
    - yarn build
  artifacts:
    paths:
      - dist
  only:
    - master
